site/laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', ['as' => 'site.home', 'uses' => 'Site\Home\HomeController@getIndex']);

Route::get('perfil/escritorio', ['as' => 'site.perfil.escritorio', 'uses' => 'Site\Perfil\PerfilController@getEscritorio']);
Route::get('perfil/arquitetos', ['as' => 'site.perfil.arquitetos', 'uses' => 'Site\Perfil\PerfilController@getArquitetos']);
Route::get('projetos', ['as' => 'site.projetos', 'uses' => 'Site\Projetos\ProjetosController@getIndex']);
Route::get('projetos/{projeto_slug}', ['as' => 'site.projetos.detalhes', 'uses' => 'Site\Projetos\ProjetosController@getDetalhes']);
Route::get('clippings', ['as' => 'site.clippings', 'uses' => 'Site\Clippings\ClippingsController@getIndex']);
Route::get('contato', ['as' => 'site.contato', 'uses' => 'Site\Contato\ContatoController@getIndex']);
Route::post('contato', ['as' => 'site.contato.enviar', 'uses' => 'Site\Contato\ContatoController@postEnviar']);
// NOVAS ROTAS SITE

Route::get('painel/auth/login',  ['as' => 'painel.login','uses' => 'Painel\Auth\LoginController@getLogin']);
Route::post('painel/auth/login', ['as' => 'painel.auth','uses' => 'Painel\Auth\LoginController@postLogin']);
Route::get('painel/auth/logout', ['as' => 'painel.logout','uses' => 'Painel\Auth\LoginController@getLogout']);

Route::group([
  'middleware' => 'auth',
  'namespace' => 'Painel',
  'prefix' => 'painel'
], function() {

  	Route::get('', ['as' => 'painel.dashboard', 'uses' => function() {
    	return view('painel.dashboard.index');
  	}]);

  	Route::post('gravaOrdem', function(Illuminate\Http\Request $request){
    	$itens = $request->input('data');
    	$tabela = $request->input('tabela');
    	for ($i = 0; $i < count($itens); $i++)
    		DB::table($tabela)->where('id', $itens[$i])->update(array('ordem' => $i));
  	});

  	Route::resource('usuarios', 'Usuarios\UsuariosController', ['as' => 'painel']);
  	Route::post('imagens/upload', 'Imagens\ImagensController@postUpload');
  	Route::get('contatos_recebidos/export', ['as' => 'painel.contatos_recebidos.export', 'uses' => 'ContatosRecebidos\ContatosRecebidosController@export']);

  	// NOVAS ROTAS DO PAINEL:
	Route::resource('banners', 'Banners\BannersController', ['only' => ['index', 'create', 'store', 'edit', 'update', 'destroy'], 'as' => 'painel']);
	Route::resource('perfil_escritorio', 'PerfilEscritorio\PerfilEscritorioController', ['only' => ['index', 'edit', 'update'], 'as' => 'painel']);
	Route::resource('perfil_arquitetos', 'PerfilArquitetos\PerfilArquitetosController', ['only' => ['index', 'create', 'store', 'edit', 'update', 'destroy'], 'as' => 'painel']);
	Route::resource('categorias', 'Categorias\CategoriasController', ['only' => ['index', 'create', 'store', 'edit', 'update', 'destroy'], 'as' => 'painel']);
	Route::resource('projetos', 'Projetos\ProjetosController', ['only' => ['index', 'create', 'store', 'edit', 'update', 'destroy'], 'as' => 'painel']);
	Route::resource('clippings', 'Clippings\ClippingsController', ['only' => ['index', 'create', 'store', 'edit', 'update', 'destroy'], 'as' => 'painel']);
	Route::resource('contato', 'Contato\ContatoController', ['only' => ['index', 'edit', 'update'], 'as' => 'painel']);
	Route::resource('contatos_recebidos', 'ContatosRecebidos\ContatosRecebidosController', ['only' => ['index', 'show', 'destroy'], 'as' => 'painel']);

});

site/laravel/app/Models/PerfilArquitetos.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class PerfilArquitetos extends Model
{

  /**
   * The database table used by the model.
   *
   * @var string
   */
  protected $table = 'perfil_arquitetos';

  /**
   * The attributes that are mass assignable.
   *
   * @var array
   */
  protected $fillable = [
    '',
  ];

  /**
   * The attributes excluded from the model's JSON form.
   *
   * @var array
   */
  protected $hidden = ['id'];

  public static function boot()
  {
	  parent::boot();

	  self::creating(function($model){
		  $model->ordem = count(PerfilArquitetos::all()) + 1;
	  });
  }

  public function scopeOrdenado($query)
  {
    return $query->orderBy('ordem', 'asc');
  }
}

site/laravel/app/Http/Controllers/Painel/Banners/BannersController.php
<?php

namespace App\Http\Controllers\Painel\Banners;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\Banner;
use App\Libs\Thumbs;

class BannersController extends Controller
{

    protected $pathImagens = 'banners/';

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index(Request $request)
    {
      	$registros = Banner::ordenado()->get();

      	return view('painel.banners.index')->with(compact('registros'));
    }

    public function create(Request $request)
    {
      	return view('painel.banners.create');
    }

    public function store(Request $request)
    {
      	$this->validate($request, [
      		'imagem' => 'required|image'
    	]);

      	$object = new Banner;

		$dt = date('dmYHis');
      	$imagem = Thumbs::make($request, 'imagem', 2000, null, $this->pathImagens, $dt);
      	if($imagem){
      		Thumbs::make($request, 'imagem', 200, 200, $this->pathImagens.'thumbs/', $dt);
      		$object->imagem = $imagem;
      	}

      	try {

        	$object->save();

        	$request->session()->flash('sucesso', 'Registro criado com sucesso.');

        	return redirect()->route('painel.banners.index');

      	} catch (\Exception $e) {

        	$request->flash();

        	return back()->withErrors(array('Erro ao criar registro! ('.$e->getMessage().')'));

      	}
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
      	return view('painel.banners.edit')->with('registro', Banner::find($id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
      	$this->validate($request, [
      		'imagem' => 'sometimes|image'
    	]);

      	$object = Banner::find($id);

		$dt = date('dmYHis');
	  	$imagem = Thumbs::make($request, 'imagem', 2000, null, $this->pathImagens, $dt);
      	if($imagem){
      		Thumbs::make($request, 'imagem', 200, 200, $this->pathImagens.'thumbs/', $dt);
      		$object->imagem = $imagem;
      	}

      	try {

        	$object->save();

        	$request->session()->flash('sucesso', 'Registro alterado com sucesso.');

        	return redirect()->route('painel.banners.index');

      	} catch (\Exception $e) {

        	$request->flash();

        	return back()->withErrors(array('Erro ao alterar registro! ('.$e->getMessage().')'));

      	}
    }

    public function destroy(Request $request, $id){
      	$object = Banner::find($id);
      	$object->delete();

      	$request->session()->flash('sucesso', 'Registro removido com sucesso.');

      	return redirect()->route('painel.banners.index');
    }

}

site/laravel/app/Http/Controllers/Painel/Categorias/CategoriasController.php
<?php

namespace App\Http\Controllers\Painel\Categorias;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\Categoria;
use App\Libs\Thumbs;

class CategoriasController extends Controller
{
    protected $pathImagens = 'categorias/';

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index(Request $request)
    {
      $registros = Categoria::ordenado()->get();

      return view('painel.categorias.index')->with(compact('registros'));
    }

    public function create(Request $request)
    {
      return view('painel.categorias.create');
    }

    public function store(Request $request)
    {
      	$this->validate($request, [
      		'titulo' => 'required|unique:categorias'
    	]);

      	$object = new Categoria;

      	$object->titulo = $request->titulo;

      	try {

        	$object->save();

        	$request->session()->flash('sucesso', 'Registro criado com sucesso.');

        	return redirect()->route('painel.categorias.index');

      	} catch (\Exception $e) {

        	$request->flash();

        	return back()->withErrors(array('Erro ao criar registro! ('.$e->getMessage().')'));

      }
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
      return view('painel.categorias.edit')->with('registro', Categoria::find($id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
      	$this->validate($request, [
      		'titulo' => 'required|unique:categorias,titulo,'.$id
    	]);

      	$object = Categoria::find($id);

      	$object->titulo = $request->titulo;

      	try {

        	$object->save();

        	$request->session()->flash('sucesso', 'Registro alterado com sucesso.');

        	return redirect()->route('painel.categorias.index');

      	} catch (\Exception $e) {

        $request->flash();

        return back()->withErrors(array('Erro ao alterar registro! ('.$e->getMessage().')'));

      }
    }

    public function destroy(Request $request, $id){
      $object = Categoria::find($id);
      $object->delete();

      $request->session()->flash('sucesso', 'Registro removido com sucesso.');

      return redirect()->route('painel.categorias.index');
    }

}

site/laravel/app/Http/Controllers/Painel/Clippings/ClippingsController.php
<?php

namespace App\Http\Controllers\Painel\Clippings;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\Clipping;
use App\Models\ClippingImagem;
use App\Libs\Thumbs;

class ClippingsController extends Controller
{
    protected $pathImagens = 'clippings/';

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index(Request $request)
    {
      	$registros = Clipping::ordenado()->get();

      	return view('painel.clippings.index')->with(compact('registros'));
    }

    public function create(Request $request)
    {
      	return view('painel.clippings.create');
    }

    public function store(Request $request)
    {
      	$this->validate($request, [
      		'titulo' => 'required',
			'capa' => 'required|image',
			'data' => 'required|date_format:m/Y'
    	]);

      	$object = new Clipping;

      	$object->titulo = $request->titulo;
      	$object->revista = $request->revista;
		$object->data = $request->data;

		$dt = date('dmYHis');
		$imagem = Thumbs::make($request, 'capa', 200, 285, $this->pathImagens, $dt);
		if($imagem){
			Thumbs::make($request, 'capa', 200, 200, $this->pathImagens.'thumbs/', $dt);
			$object->capa = $imagem;
		}

      	try {

        	$object->save();

			$imagens_albuns = $request->imagem_album;
	        if(sizeof($imagens_albuns)){
	          foreach ($imagens_albuns as $ordem => $img) {
	            $object->imagens()->save( new ClippingImagem([
	                'imagem' => $img,
	                'ordem' => $ordem
	              ])
	            );
	          }
	        }

        	$request->session()->flash('sucesso', 'Registro criado com sucesso.');

        	return redirect()->route('painel.clippings.index');

      	} catch (\Exception $e) {

        	$request->flash();

        	return back()->withErrors(array('Erro ao criar registro! ('.$e->getMessage().')'));

      	}
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
      	return view('painel.clippings.edit')->with('registro', Clipping::find($id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
      	$this->validate($request, [
			'titulo' => 'required',
			'capa' => 'sometimes|image',
			'data' => 'required|date_format:m/Y'
    	]);

      	$object = Clipping::find($id);

		$object->titulo = $request->titulo;
      	$object->revista = $request->revista;
		$object->data = $request->data;

		$dt = date('dmYHis');
		$imagem = Thumbs::make($request, 'capa', 200, 285, $this->pathImagens, $dt);
		if($imagem){
			Thumbs::make($request, 'capa', 200, 200, $this->pathImagens.'thumbs/', $dt);
			$object->capa = $imagem;
		}

      	try {

        	$object->save();

			$imgs_atuais = $object->imagens;
	        foreach ($imgs_atuais as $img_atual)
	          $img_atual->delete();

	        $imagens_albuns = $request->imagem_album;
	        if(sizeof($imagens_albuns)){
	          foreach ($imagens_albuns as $ordem => $img) {
	            $object->imagens()->save( new ClippingImagem([
	                'imagem' => $img,
	                'ordem' => $ordem
	              ])
	            );
	          }
	        }

        	$request->session()->flash('sucesso', 'Registro alterado com sucesso.');

        	return redirect()->route('painel.clippings.index');

      	} catch (\Exception $e) {

        	$request->flash();

        	return back()->withErrors(array('Erro ao alterar registro! ('.$e->getMessage().')'));

      	}
    }

    public function destroy(Request $request, $id){
      	$object = Clipping::find($id);
      	$object->delete();

      	$request->session()->flash('sucesso', 'Registro removido com sucesso.');

      	return redirect()->route('painel.clippings.index');
    }

}

site/laravel/app/Http/Controllers/Painel/Contato/ContatoController.php
<?php

namespace App\Http\Controllers\Painel\Contato;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\Contato;
use App\Libs\Thumbs;

class ContatoController extends Controller
{
    protected $pathImagens = 'contato/';

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index(Request $request)
    {
      	$registros = Contato::all();

      	return view('painel.contato.index')->with(compact('registros'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
      	return view('painel.contato.edit')->with('registro', Contato::find($id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
      	$this->validate($request, [
      		'email_contato' => 'required|email'
    	]);

      	$object = Contato::find($id);

		$object->texto = $request->texto;
		$object->email_contato = $request->email_contato;
		$object->analytics = $request->analytics;
		$object->facebook = $request->facebook;
		$object->instagram = $request->instagram;
		$object->google_maps = $request->google_maps;
		$object->google_maps_alt = $request->google_maps_alt;


      	try {

        	$object->save();

        	$request->session()->flash('sucesso', 'Registro alterado com sucesso.');

        	return redirect()->route('painel.contato.index');

      	} catch (\Exception $e) {

        	$request->flash();

        	return back()->withErrors(array('Erro ao alterar registro! ('.$e->getMessage().')'));

      }
    }

}

site/laravel/app/Http/Controllers/Painel/ContatosRecebidos/ContatosRecebidosController.php
<?php

namespace App\Http\Controllers\Painel\ContatosRecebidos;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\ContatoRecebido;
use App\Libs\Thumbs;
use League\Csv\Writer;

class ContatosRecebidosController extends Controller
{
    protected $pathImagens = 'contatos_recebidos/';

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index(Request $request)
    {
      $registros = ContatoRecebido::ordenado()->get();

      return view('painel.contatos_recebidos.index')->with(compact('registros'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
      return view('painel.contatos_recebidos.show')->with('registro', ContatoRecebido::find($id));
    }

	public function destroy(Request $request, $id)
    {
		$object = ContatoRecebido::find($id);
		$object->delete();

		$request->session()->flash('sucesso', 'Registro removido com sucesso.');

		return redirect()->route('painel.contatos_recebidos.index');
    }

    public function export(Request $request)
    {
		$contatos = ContatoRecebido::ordenado()->get();

        $csv = Writer::createFromFileObject(new \SplTempFileObject());

        $csv->insertOne(['Nome', 'E-mail', 'Mensagem', 'Data']);

        foreach ($contatos as $contato) {
            $csv->insertOne([
				'nome' => $contato->nome,
				'email' => $contato->email,
				'mensagem' => $contato->mensagem,
				'data' => $contato->created_at->format('d/m/Y H:i:s')
			]);
        }

        $csv->output('contatos_recebidos_'.date('d_m_Y_H_i').'.csv');
    }

}

site/laravel/resources/views/painel/perfil_arquitetos/create.blade.php
@extends('painel.template')

@section('conteudo')

<div class="container-fluid padded-bottom">

	<div class="row">
		<div class="col-xs-12 col-sm-8 col-md-6 col-lg-6">

      		<h2>Cadastrar Arquiteto</h2>

	        <hr>

	        @include('painel.partials.mensagens')

		</div>
	</div>

    <form action="{{ URL::route('painel.perfil_arquitetos.store') }}" method="post" enctype="multipart/form-data">

  		{!! csrf_field() !!}

  		<div class="row">
  			<div class="col-xs-12 col-sm-8 col-md-6 col-lg-6">

            	<div class="form-group">
  					<label for="inputTitulo">Nome</label>
  					<input type="text" name="nome" class="form-control" id="inputTitulo" value="{{old('nome')}}">
  				</div>

  			    <div class="form-group">
  					<label for="inputTexto">Texto</label>
  					<textarea name="texto" class="form-control textarea-simples" id="inputTexto">{{old('texto')}}</textarea>
  				</div>

				<div class="form-group">
					@if(old('imagem'))
						Imagem atual<br>
						<img src="assets/images/perfil_arquitetos/{{old('imagem')}}"><br>
					@endif
					<label for="inputImagem">Imagem</label>
					<input type="file" class="form-control" id="inputImagem" name="imagem">
				</div>

            	<hr>

  			</div>
  		</div>

		<button type="submit" title="Cadastrar" class="btn btn-success">Cadastrar</button>

		<a href="{{ URL::route('painel.perfil_arquitetos.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

	</form>

</div>

@endsection

site/laravel/resources/views/painel/perfil_arquitetos/edit.blade.php
@extends('painel.template')

@section('conteudo')

<div class="container-fluid padded-bottom">

    <div class="row">
    	<div class="col-xs-12 col-sm-8 col-md-6 col-lg-6">

		  	<h2>Editar Arquiteto</h2>

		    <hr>

		    @include('painel.partials.mensagens')

		</div>
	</div>

    <form action="{{ URL::route('painel.perfil_arquitetos.update', $registro->id) }}" method="post" enctype="multipart/form-data">

		<input type="hidden" name="_method" value="PUT">

		{!! csrf_field() !!}

		<div class="row">
			<div class="col-xs-12 col-sm-8 col-md-6 col-lg-6">

          		<div class="form-group">
            		<label for="inputTitulo">Nome</label>
            		<input type="text" name="nome" class="form-control" id="inputTitulo" value="{{$registro->nome}}">
          		</div>

			    <div class="form-group">
					<label for="inputTexto">Texto</label>
					<textarea name="texto" class="form-control textarea-simples" id="inputTexto">{{$registro->texto}}</textarea>
				</div>

				<div class="form-group">
					@if($registro->imagem)
						Imagem atual<br>
						<img src="assets/images/perfil_arquitetos/{{$registro->imagem}}" class="img-thumbnail"><br>
					@endif
					<label for="inputImagem">Imagem</label>
					<input type="file" class="form-control" id="inputImagem" name="imagem">
				</div>

          		<hr>

			</div>
		</div>

		<button type="submit" title="Alterar" class="btn btn-success">Alterar</button>

		<a href="{{ URL::route('painel.perfil_arquitetos.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

	</form>

</div>

@endsection

site/laravel/resources/views/painel/perfil_arquitetos/index.blade.php
@extends('painel.template')

@section('conteudo')

  <div class="container-fluid padded-bottom">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

        <h2>Perfil - Arquitetos</h2>

        <hr>

      	@include('painel.partials.mensagens')

        <a href="{{ URL::route('painel.perfil_arquitetos.create') }}" class="btn btn-success btn-sm"><span class="glyphicon glyphicon-plus-sign"></span> Adicionar Arquiteto</a>

        <table class="table table-striped table-bordered table-hover table-sortable" data-tabela='perfil_arquitetos'>

          <thead>
          	<tr>
              	<th>Ordenar</th>
          		<th>Nome</th>
          		<th><span class="glyphicon glyphicon-cog"></span></th>
          	</tr>
        	</thead>
        	<tbody>
          	@foreach ($registros as $registro)

            	<tr class="tr-row" id="row_{{ $registro->id }}">
	                <td class='move-actions'><a href='#' class='btn btn-info btn-move btn-sm'>mover</a></td>
	                <td>
	                  {{$registro->nome}}
	                </td>
	            	<td class="crud-actions">
	              		<a href="{{ URL::route('painel.perfil_arquitetos.edit', $registro->id ) }}" class="btn btn-primary btn-sm">editar</a>

	                  <form action="{{ URL::route('painel.perfil_arquitetos.destroy', $registro->id) }}" method="post">
	                    {!! csrf_field() !!}
	                    <input type="hidden" name="_method" value="DELETE">
	                    <button type="submit" class="btn btn-danger btn-sm btn-delete">excluir</button>
	                  </form>
            		</td>
            	</tr>

          	@endforeach
        	</tbody>

      	</table>

      </div>
    </div>
  </div>

@endsection